services:
  - type: web
    name: tocrown
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SQLSERVER_CONNECTION_STRING
        sync: false
